# Generated by Django 5.0.2 on 2024-02-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="count",
            field=models.IntegerField(null=True),
        ),
    ]
